# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\animation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1006, 857)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.control_group = QtWidgets.QGroupBox(Dialog)
        self.control_group.setObjectName("control_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.control_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.play_button = QtWidgets.QPushButton(self.control_group)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/play.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.play_button.setIcon(icon)
        self.play_button.setObjectName("play_button")
        self.horizontalLayout_2.addWidget(self.play_button)
        self.pause_button = QtWidgets.QPushButton(self.control_group)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/pause.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pause_button.setIcon(icon1)
        self.pause_button.setObjectName("pause_button")
        self.horizontalLayout_2.addWidget(self.pause_button)
        self.stop_button = QtWidgets.QPushButton(self.control_group)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/stop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stop_button.setIcon(icon2)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout_2.addWidget(self.stop_button)
        self.loop_animation = QtWidgets.QCheckBox(self.control_group)
        self.loop_animation.setObjectName("loop_animation")
        self.horizontalLayout_2.addWidget(self.loop_animation)
        self.show_boxes = QtWidgets.QCheckBox(self.control_group)
        self.show_boxes.setObjectName("show_boxes")
        self.horizontalLayout_2.addWidget(self.show_boxes)
        self.show_effects = QtWidgets.QCheckBox(self.control_group)
        self.show_effects.setObjectName("show_effects")
        self.horizontalLayout_2.addWidget(self.show_effects)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.frame_slider = QtWidgets.QSlider(self.control_group)
        self.frame_slider.setOrientation(QtCore.Qt.Horizontal)
        self.frame_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.frame_slider.setObjectName("frame_slider")
        self.verticalLayout_2.addWidget(self.frame_slider)
        self.verticalLayout.addWidget(self.control_group)
        self.animation_view = QtWidgets.QGraphicsView(Dialog)
        self.animation_view.setObjectName("animation_view")
        self.verticalLayout.addWidget(self.animation_view)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.control_group.setTitle(_translate("Dialog", "Controls"))
        self.play_button.setText(_translate("Dialog", "Play"))
        self.pause_button.setText(_translate("Dialog", "Pause"))
        self.stop_button.setText(_translate("Dialog", "Stop"))
        self.loop_animation.setText(_translate("Dialog", "Loop"))
        self.show_boxes.setText(_translate("Dialog", "Show Hit/Hurt boxes"))
        self.show_effects.setText(_translate("Dialog", "Show Effects"))
from bbsed.ui import resources_rc
