# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\extra_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Extra(object):
    def setupUi(self, Extra):
        Extra.setObjectName("Extra")
        Extra.resize(400, 20)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Extra)
        self.horizontalLayout.setContentsMargins(4, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.state_name = QtWidgets.QLabel(Extra)
        self.state_name.setText("")
        self.state_name.setObjectName("state_name")
        self.horizontalLayout.addWidget(self.state_name)
        self.state_choices = QtWidgets.QComboBox(Extra)
        self.state_choices.setObjectName("state_choices")
        self.horizontalLayout.addWidget(self.state_choices)

        self.retranslateUi(Extra)
        QtCore.QMetaObject.connectSlotsByName(Extra)

    def retranslateUi(self, Extra):
        _translate = QtCore.QCoreApplication.translate
        Extra.setWindowTitle(_translate("Extra", "Form"))
