# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_path = QtWidgets.QPushButton(self.groupBox)
        self.select_path.setObjectName("select_path")
        self.horizontalLayout.addWidget(self.select_path)
        self.bbcf_path = QtWidgets.QLineEdit(self.groupBox)
        self.bbcf_path.setEnabled(False)
        self.bbcf_path.setObjectName("bbcf_path")
        self.horizontalLayout.addWidget(self.bbcf_path)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.char_select = QtWidgets.QComboBox(self.groupBox_2)
        self.char_select.setObjectName("char_select")
        self.horizontalLayout_2.addWidget(self.char_select)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.sprite_group = QtWidgets.QGroupBox(self.centralwidget)
        self.sprite_group.setObjectName("sprite_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sprite_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.sprite_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.palette_select = QtWidgets.QComboBox(self.sprite_group)
        self.palette_select.setObjectName("palette_select")
        self.horizontalLayout_3.addWidget(self.palette_select)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.file_list = QtWidgets.QListWidget(self.sprite_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file_list.sizePolicy().hasHeightForWidth())
        self.file_list.setSizePolicy(sizePolicy)
        self.file_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.file_list.setObjectName("file_list")
        self.horizontalLayout_4.addWidget(self.file_list)
        self.sprite_preview = QtWidgets.QGraphicsView(self.sprite_group)
        self.sprite_preview.setObjectName("sprite_preview")
        self.horizontalLayout_4.addWidget(self.sprite_preview)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.sprite_group)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "BBCF Installation"))
        self.select_path.setText(_translate("MainWindow", "Select"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Character"))
        self.sprite_group.setTitle(_translate("MainWindow", "Sprite"))
        self.label.setText(_translate("MainWindow", "Palette"))
