# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\select_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 638)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.character_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.character_select.sizePolicy().hasHeightForWidth())
        self.character_select.setSizePolicy(sizePolicy)
        self.character_select.setObjectName("character_select")
        self.horizontalLayout_26.addWidget(self.character_select)
        self.palette_select = QtWidgets.QComboBox(Dialog)
        self.palette_select.setObjectName("palette_select")
        self.horizontalLayout_26.addWidget(self.palette_select)
        self.slot_select = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slot_select.sizePolicy().hasHeightForWidth())
        self.slot_select.setSizePolicy(sizePolicy)
        self.slot_select.setObjectName("slot_select")
        self.horizontalLayout_26.addWidget(self.slot_select)
        self.ms_checkbox = QtWidgets.QCheckBox(Dialog)
        self.ms_checkbox.setEnabled(False)
        self.ms_checkbox.setText("")
        self.ms_checkbox.setObjectName("ms_checkbox")
        self.horizontalLayout_26.addWidget(self.ms_checkbox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.sprite_preview = QtWidgets.QGraphicsView(Dialog)
        self.sprite_preview.setObjectName("sprite_preview")
        self.verticalLayout.addWidget(self.sprite_preview)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
