# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\selector_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selector(object):
    def setupUi(self, Selector):
        Selector.setObjectName("Selector")
        Selector.resize(215, 20)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Selector)
        self.horizontalLayout.setContentsMargins(1, 0, 4, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.char_select = QtWidgets.QComboBox(Selector)
        self.char_select.setObjectName("char_select")
        self.horizontalLayout.addWidget(self.char_select)
        self.palette_select = QtWidgets.QComboBox(Selector)
        self.palette_select.setObjectName("palette_select")
        self.horizontalLayout.addWidget(self.palette_select)
        self.slot_select = QtWidgets.QComboBox(Selector)
        self.slot_select.setObjectName("slot_select")
        self.horizontalLayout.addWidget(self.slot_select)

        self.retranslateUi(Selector)
        QtCore.QMetaObject.connectSlotsByName(Selector)

    def retranslateUi(self, Selector):
        _translate = QtCore.QCoreApplication.translate
        Selector.setWindowTitle(_translate("Selector", "Form"))
