# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\settingsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 105)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.steam_group = QtWidgets.QGroupBox(Dialog)
        self.steam_group.setObjectName("steam_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.steam_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select = QtWidgets.QPushButton(self.steam_group)
        self.select.setObjectName("select")
        self.horizontalLayout.addWidget(self.select)
        self.steam_install = QtWidgets.QLineEdit(self.steam_group)
        self.steam_install.setEnabled(False)
        self.steam_install.setObjectName("steam_install")
        self.horizontalLayout.addWidget(self.steam_install)
        self.verticalLayout.addWidget(self.steam_group)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.steam_group.setTitle(_translate("Dialog", "Steam Install"))
        self.select.setText(_translate("Dialog", "Select"))
