# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\sprite_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(886, 627)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Editor.sizePolicy().hasHeightForWidth())
        Editor.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Editor)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.character_group = QtWidgets.QGroupBox(Editor)
        self.character_group.setObjectName("character_group")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.character_group)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.char_select = QtWidgets.QComboBox(self.character_group)
        self.char_select.setObjectName("char_select")
        self.horizontalLayout.addWidget(self.char_select)
        self.palette_select = QtWidgets.QComboBox(self.character_group)
        self.palette_select.setObjectName("palette_select")
        self.horizontalLayout.addWidget(self.palette_select)
        self.slot_select = QtWidgets.QComboBox(self.character_group)
        self.slot_select.setObjectName("slot_select")
        self.horizontalLayout.addWidget(self.slot_select)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.character_group)
        self.sprite_group = QtWidgets.QGroupBox(Editor)
        self.sprite_group.setObjectName("sprite_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sprite_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sprite_list = QtWidgets.QTreeWidget(self.sprite_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprite_list.sizePolicy().hasHeightForWidth())
        self.sprite_list.setSizePolicy(sizePolicy)
        self.sprite_list.setObjectName("sprite_list")
        self.sprite_list.header().setVisible(False)
        self.horizontalLayout_2.addWidget(self.sprite_list)
        self.sprite_preview = QtWidgets.QGraphicsView(self.sprite_group)
        self.sprite_preview.setObjectName("sprite_preview")
        self.horizontalLayout_2.addWidget(self.sprite_preview)
        self.verticalLayout.addWidget(self.sprite_group)
        self.play_animation = QtWidgets.QAction(Editor)
        self.play_animation.setObjectName("play_animation")
        self.detail_img_info = QtWidgets.QAction(Editor)
        self.detail_img_info.setObjectName("detail_img_info")

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        Editor.setWindowTitle(_translate("Editor", "Form"))
        self.character_group.setTitle(_translate("Editor", "Character + Palette + Slot"))
        self.sprite_group.setTitle(_translate("Editor", "Sprite"))
        self.sprite_list.headerItem().setText(0, _translate("Editor", "Animations"))
        self.play_animation.setText(_translate("Editor", "Play Animation"))
        self.detail_img_info.setText(_translate("Editor", "Detailed Image Info"))
