# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bbsed\ui\sprite_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(886, 627)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Editor.sizePolicy().hasHeightForWidth())
        Editor.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Editor)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sprite_list = QtWidgets.QTreeWidget(Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprite_list.sizePolicy().hasHeightForWidth())
        self.sprite_list.setSizePolicy(sizePolicy)
        self.sprite_list.setObjectName("sprite_list")
        self.sprite_list.header().setVisible(False)
        self.horizontalLayout.addWidget(self.sprite_list)
        self.sprite_preview = QtWidgets.QGraphicsView(Editor)
        self.sprite_preview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sprite_preview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.sprite_preview.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.sprite_preview.setObjectName("sprite_preview")
        self.horizontalLayout.addWidget(self.sprite_preview)
        self.show_animation_info = QtWidgets.QAction(Editor)
        self.show_animation_info.setObjectName("show_animation_info")

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        Editor.setWindowTitle(_translate("Editor", "Form"))
        self.sprite_list.headerItem().setText(0, _translate("Editor", "Animations"))
        self.show_animation_info.setText(_translate("Editor", "View Animation Details"))
        self.show_animation_info.setToolTip(_translate("Editor", "View animation game information"))
