DEFAULT_PALETTE_FMT = "{}{{}}_00.hpl"

SPRITE_FILES = 1
EFFECT_FILES = 2
CHARACTER_STATES = 3

IGNORE_FILES = 0
GROUP_FILES = 1
HIP_FILE_LIST = 2
PALETTE_FILE = 3
STATE_DEFINITION = 4
STATE_INITIAL = 5
STATE_CHANGE = 6

SWAP_COLORS = 0
SWAP_PALETTES = 1
SWAP_INDICES = 2
