DEFAULT_PALETTE_FMT = "{}{{}}_00.hpl"

SPRITE_FILES = 1
EFFECT_FILES = 2
CHARACTER_STATES = 3

IGNORE_FILES = 0
GROUP_FILES = 1

HIP_FILE_LIST = 0
PALETTE_FILE = 1
STATE_DEFINITION = 2
STATE_INITIAL = 3
STATE_CHANGE = 4

SWAP_COLORS = 0
SWAP_PALETTES = 1
SWAP_INDICES = 2
